services:
  app:
    build: .
    container_name: cv-generator
    volumes:
      - ./:/app
      - ./generated_cvs:/app/generated_cvs
    working_dir: /app
    stdin_open: true
    tty: true
    command: tail -f /dev/null